var hierarchy =
[
    [ "aspl::Client", "classaspl_1_1_client.html", null ],
    [ "aspl::ClientInfo", "structaspl_1_1_client_info.html", null ],
    [ "aspl::Context", "structaspl_1_1_context.html", null ],
    [ "aspl::ControlRequestHandler", "classaspl_1_1_control_request_handler.html", null ],
    [ "aspl::DeviceParameters", "structaspl_1_1_device_parameters.html", null ],
    [ "aspl::Dispatcher", "classaspl_1_1_dispatcher.html", null ],
    [ "aspl::DoubleBuffer< T >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< AudioStreamBasicDescription >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::array< UInt32, 2 > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::map< AudioObjectPropertyScope, std::map< AudioObjectID, std::shared_ptr< aspl::Object > > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::map< AudioObjectPropertySelector, std::shared_ptr< CustomProperty > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::optional< std::vector< AudioChannelDescription > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::optional< std::vector< AudioStreamRangedDescription > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::optional< std::vector< AudioValueRange > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::optional< std::vector< UInt8 > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::optional< UInt32 > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::shared_ptr< aspl::MuteControl > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::shared_ptr< aspl::VolumeControl > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< AudioObjectID, std::shared_ptr< aspl::Device > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< AudioObjectID, std::shared_ptr< aspl::MuteControl > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< AudioObjectID, std::shared_ptr< aspl::Stream > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< AudioObjectID, std::shared_ptr< aspl::VolumeControl > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< AudioObjectID, std::shared_ptr< Registration > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< AudioObjectPropertyScope, std::vector< std::shared_ptr< aspl::MuteControl > > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< AudioObjectPropertyScope, std::vector< std::shared_ptr< aspl::VolumeControl > > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< Direction, std::vector< std::shared_ptr< aspl::Stream > > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< std::string, std::shared_ptr< aspl::Device > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::unordered_map< UInt32, std::shared_ptr< aspl::Client > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::variant< std::shared_ptr< aspl::DriverRequestHandler >, aspl::DriverRequestHandler * > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::variant< std::shared_ptr< aspl::IORequestHandler >, aspl::IORequestHandler * > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::DoubleBuffer< std::vector< std::shared_ptr< aspl::Device > > >", "classaspl_1_1_double_buffer.html", null ],
    [ "aspl::Driver", "classaspl_1_1_driver.html", null ],
    [ "aspl::DriverRequestHandler", "classaspl_1_1_driver_request_handler.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "aspl::Object", "classaspl_1_1_object.html", [
        [ "aspl::Device", "classaspl_1_1_device.html", null ],
        [ "aspl::MuteControl", "classaspl_1_1_mute_control.html", null ],
        [ "aspl::Plugin", "classaspl_1_1_plugin.html", null ],
        [ "aspl::Stream", "classaspl_1_1_stream.html", null ],
        [ "aspl::VolumeControl", "classaspl_1_1_volume_control.html", null ]
      ] ]
    ] ],
    [ "aspl::Tracer::Flags", "structaspl_1_1_tracer_1_1_flags.html", null ],
    [ "aspl::IORequestHandler", "classaspl_1_1_i_o_request_handler.html", null ],
    [ "aspl::MuteControlParameters", "structaspl_1_1_mute_control_parameters.html", null ],
    [ "aspl::Tracer::Operation", "structaspl_1_1_tracer_1_1_operation.html", null ],
    [ "aspl::PluginParameters", "structaspl_1_1_plugin_parameters.html", null ],
    [ "aspl::DoubleBuffer< T >::ReadLock", "classaspl_1_1_double_buffer_1_1_read_lock.html", null ],
    [ "aspl::Storage", "classaspl_1_1_storage.html", null ],
    [ "aspl::StreamParameters", "structaspl_1_1_stream_parameters.html", null ],
    [ "aspl::Tracer", "classaspl_1_1_tracer.html", null ],
    [ "aspl::VolumeControlParameters", "structaspl_1_1_volume_control_parameters.html", null ]
];