// Copyright (c) libASPL authors
// Licensed under MIT

#pragma once

#include <aspl/Tracer.hpp>
#include <aspl/util/MpscQueue.hpp>
#include <aspl/util/ObjectPool.hpp>
#include <aspl/util/Semaphore.hpp>

#include <CoreAudio/AudioServerPlugIn.h>

#include <atomic>
#include <chrono>
#include <memory>
#include <mutex>
#include <optional>
#include <shared_mutex>
#include <string>
#include <unordered_map>
#include <vector>

namespace aspl {

//! Event types generated by VirtualHost.
enum class VirtualEventType
{
    //! Generated by VirtualHost::PropertiesChanged().
    //! Triggered by driver whenever a property of any object changes.
    //! See Object::NotifyPropertyChanged() for details.
    ObjectPropertyChange,

    //! Generated by VirtualHost::RequestDeviceConfigurationChange().
    //! Triggered by driver when it needs to re-configure device.
    //! See Device::RequestConfigurationChange() for details.
    DeviceConfigurationRequest,

    //! Generated by VirtualHost::WriteToStorage() and VirtualHost::DeleteFromStorage().
    //! Triggered by driver when it updates persistent storage.
    //! See Driver::GetStorage() for details.
    StorageDataChange,

    //! Generated by VirtualHost when virtual IO timer ticks.
    //! This is artificial event that you can use to simulate I/O.
    //! See VirtualHostParameters::TicksPerSecond for details.
    IOTimerTick,

    //! Something else.
    //! Use if you want to subclass VirtualEventInfo and introduce your own type.
    CustomEvent,
};

//! Event data generated by VirtualHost.
//!
//! When corresponding event happens, VirtualHost allocates event info struct from
//! pool, populates it with relevant data, and pushes to event queue.
//!
//! The user can fetch events from the queue using WaitEvent() or ReadEvent().
struct VirtualEventInfo : util::MpscNode
{
    //! Payload for ObjectPropertyChange event.
    struct ObjectPropertyChangeInfo
    {
        //! Identifies object which property changed.
        AudioObjectID ObjectID = 0;

        //! Identifies property which changed.
        AudioObjectPropertyAddress PropertyAddress = {};
    };

    //! Payload for DeviceConfigurationRequest event.
    struct DeviceConfigurationRequestInfo
    {
        //! Identifies device which requested configuration.
        AudioObjectID DeviceID = 0;

        //! Action identifier to be passed to PerformConfigurationChange.
        UInt64 ChangeAction = 0;

        //! Extra argument to be passed to PerformConfigurationChange.
        void* ChangeInfo = nullptr;
    };

    //! Payload for StorageDataChange event.
    struct StorageDataChangeInfo
    {
        //! Identifies updated or deleted storage entry.
        std::string StorageKey;
    };

    //! Payload for IOTimerTick event.
    struct IOTimerTickInfo
    {
        //! Scheduled tick time.
        std::chrono::steady_clock::time_point Time;

        //! Incrementing tick counter.
        SInt64 Number = 0;
    };

    //! Construct event info.
    explicit VirtualEventInfo(VirtualEventType eventType)
        : EventType(eventType)
    {
    }

    virtual ~VirtualEventInfo() = default;

    //! Event type.
    //! Depending on the type, one of the payload optionals below is populated
    //! with type-specific information.
    VirtualEventType EventType;

    //! Time when event was generated in producer thread, as reported by
    //! GetCurrentTimeImpl().
    std::chrono::steady_clock::time_point EnqueueTime;

    //! Time when event was delivered to consumer thread, as reported by
    //! GetCurrentTimeImpl().
    std::chrono::steady_clock::time_point DequeueTime;

    //! Payload for ObjectPropertyChange event.
    std::optional<ObjectPropertyChangeInfo> ObjectPropertyChange;

    //! Payload for DeviceConfigurationRequest event.
    std::optional<DeviceConfigurationRequestInfo> DeviceConfigurationRequest;

    //! Payload for StorageDataChange event.
    std::optional<StorageDataChangeInfo> StorageDataChange;

    //! Payload for IOTimerTick event.
    std::optional<IOTimerTickInfo> IOTimerTick;
};

//! Virtual host parameters.
struct VirtualHostParameters
{
    //! How frequently to generate virtual IOTimerTick events.
    //! When zero (default), no timer ticks are generated.
    //! When non-zero, defines ticks per second for virtual I/O timer.
    //! Used by default implementation of VirtualHost tick methods.
    double TicksPerSecond = 0.0;

    //! Safety zone to suppress events too close to I/O tick.
    //! When non-zero, when the time till next tick is less than this duration,
    //! WaitEvent() and ReadEvent() ignore all events except I/O tick events.
    //! Useful when you process events and I/O in real-time. Allows to be sure that
    //! event processing won't delay upcoming I/O operation.
    //! Used by default implementation of VirtualHost tick methods.
    std::chrono::steady_clock::duration TickSafetyZone{};

    //! Whether to skip event for IO tick if it's too late.
    //! If you're processing events and I/O in real-time, most likely you want
    //! to set this to true.
    //! When true, I/O tick event is generated for nearest tick that is at or after
    //! the current time, skipping any ticks that are already late.
    //! When false, events is always generated for the next sequential tick
    //! regardless of current time.
    //! Used by default implementation of VirtualHost tick methods.
    bool SkipLateTicks = true;

    //! Whether to trace event operations (WaitEvent, ReadEvent, EnqueueEvent).
    //! Used by default implementation of VirtualHost event methods.
    bool EnableEventTracing = true;

    //! Whether to trace IOTimerTick events in addition to other events.
    //! Only has effect when EnableEventTracing is also true.
    //! Used by default implementation of VirtualHost event methods.
    bool EnableIOTracing = false;

    //! Whether to trace storage operations (CopyFromStorage, WriteToStorage,
    //! DeleteFromStorage).
    //! Used by default implementation of VirtualHost storage methods.
    bool EnableStorageTracing = true;
};

//! Virtual HAL host for blackbox testing of audio plugins.
//!
//! This class provides a minimal mock implementation of AudioServerPlugInHost, that is
//! normally implemented by macOS audio server and exposed to plugins. You can use it for
//! testing of your plugin in simulated environments outside of audio server, e.g. to
//! write integration tests or debugging tools.
//!
//! The host interface allows plugins to:
//! - Notify about property changes
//! - Request device configuration changes
//! - Access persistent storage (key-value database)
//!
//! When some of the above happens, VirtualHost generates event and places it into the
//! event queue. The user can fetch queued events using WaitEvent() and ReadEvent().
//!
//! VirtualHost tries to minimize assumptions about the use case and implements only
//! low-level boilerplate, leaving all higher-level logic to the user:
//!
//!   - It's up to you how to respond to events. Normally driver will expect some
//!     reasonable behavior from plugin host, but you may want to test edge cases.
//!
//!   - It's up to you whether to process events in real-time (or sort of), or just
//!     test logical sequence of requests to driver and responses.
//!
//!   - Thread management is also on you. VirtualHost does not run any threads. It uses
//!     lock-free queue and pool for events, and support both multi-threaded and
//!     single-threaded use.
//!
//! If you enable I/O timer in VirtualHostParameters, in addition to events triggered by
//! driver, VirtualHost will also generate I/O tick events. These ticks are purely
//! virtual, they appear only when you read an event. This feature is convenient if you
//! want to handle event processing and I/O uniformly (e.g. in an event loop).
//!
//! You can also generate your own events (including I/O ticks) using AllocateEvent() and
//! EnqueueEvent() methods. VirtualHost will just place your event to the queue; again,
//! this may be useful if you want to handle built-in and custom events uniformly.
//!
//! To introduce custom event types, you may subclass VirtualEventInfo. In this case
//! you'll need to allocate events by yourself. Consider using aspl::util::ObjectPool.
//!
//! You can also inherit VirtualHost and override implementation for event management,
//! virtual I/O timer, and virtual storage.
class VirtualHost
{
public:
    //! Construct virtual host.
    explicit VirtualHost(std::shared_ptr<Tracer> tracer = {},
        const VirtualHostParameters& params = {});

    VirtualHost(const VirtualHost&) = delete;
    VirtualHost& operator=(const VirtualHost&) = delete;

    virtual ~VirtualHost();

    //! Get reference to the host vtable.
    //!
    //! This is what should be passed to the driver's Initialize() method.
    //! The returned reference remains valid for the lifetime of this object.
    AudioServerPlugInHostRef GetReference();

    //! @name Virtual events
    //! @{

    //! Check if events are available for reading.
    //!
    //! Called by user.
    //! Returns true if events are available for reading immediately.
    //! Takes into account I/O timer and tick safety zones (if enabled).
    //!
    //! @note
    //!  If you use VirtualHost from multiple threads, returned value may be outdated.
    //!
    //! @remarks
    //!  Invokes PendingEventsImpl() and GetNextTickImpl() and related functions.
    //!  Default implementation is real-time safe.
    bool HasAvailEvents() const;

    //! Wait for event from queue.
    //!
    //! Called by user.
    //! Blocks until an event is available.
    //! Takes into account I/O timer and tick safety zones (if enabled).
    //! If deadline is provided, if there is no event until it's reached, returns null.
    //! Deadline must be absolute timestamp in steady (a.k.a. monotonic) clock domain.
    //!
    //! @remarks
    //!  Invokes WaitEventImpl() and GetNextTickImpl() and related functions.
    //!  Default implementation is real-time safe.
    std::shared_ptr<VirtualEventInfo> WaitEvent(
        std::optional<std::chrono::steady_clock::time_point> deadline = {});

    //! Read event from queue without blocking.
    //!
    //! Called by user.
    //! Never blocks.
    //! Takes into account I/O timer and tick safety zones (if enabled).
    //! Returns nullptr if no events are available immediately.
    //!
    //! @remarks
    //!  Invokes ReadEventImpl() and GetNextTickImpl() and related functions.
    //!  Default implementation is real-time safe.
    std::shared_ptr<VirtualEventInfo> ReadEvent();

    //! Allocate event from pool.
    //!
    //! Called by user and by VirtualHost.
    //! Returns event with all fields except type cleared.
    //! The caller is expected to populate event fields and pass it to EnqueueEvent().
    //!
    //! @remarks
    //!  Invokes AllocateEventIml(). Default implementation is real-time safe.
    //!  When shared_ptr is released, event is returned to pool.
    std::shared_ptr<VirtualEventInfo> AllocateEvent(VirtualEventType eventType);

    //! Enqueue event for processing.
    //!
    //! Called by user and by VirtualHost.
    //! Adds event to the queue and signals one of the waiting thread(s).
    //!
    //! @note
    //!  VirtualHost produces events but doesn't handle them, it's up to the user.
    //!  Usually AllocateEvent() and EnqueueEvent() are called by VirtualHost,
    //!  but user can do it too. E.g. if you may want to generate I/O ticks by yourself
    //!  and then process them uniformly with other virtual events.
    //!
    //! @remarks
    //!  Invokes EnqueueEventImpl(). Default implementation is real-time safe
    //!  and does not make allocations.
    void EnqueueEvent(std::shared_ptr<VirtualEventInfo> event);

    //! Abort all current and future blocking calls.
    //!
    //! Called by user.
    //! Wakes up any pending calls to WaitEvent().
    //! All future calls to WaitEvent() and ReadEvent() will immediately return null.
    //!
    //! @remarks
    //!  Invokes AbortEventsImpl(). Default implementation is real-time safe.
    void AbortEvents();

    // @}

    //! @name Requests from driver
    //! @{

    //! Handle property change notification from plugin.
    //!
    //! Called by driver (via host vtable) to notify the host that properties of an object
    //! have changed. The host is expected to update its internal state and/or notify
    //! interested clients.
    //!
    //! See Object::NotifyPropertyChanged().
    //!
    //! @remarks
    //!  Default implementation triggers ObjectPropertyChange event(s), one event for
    //!  every listed property address.
    virtual OSStatus PropertiesChanged(AudioObjectID objectID,
        UInt32 numberAddresses,
        const AudioObjectPropertyAddress* addresses);

    //! Handle request for device configuration change.
    //!
    //! Called when the plugin wants to change device configuration in a way that affects
    //! I/O or device structure. The host is expected to stop any active I/O, tell
    //! device to apply changes, and restart I/O.
    //!
    //! See Device::PerformConfigurationChange().
    //!
    //! @remarks
    //!  Default implementation triggers DeviceConfigurationRequest event.
    virtual OSStatus RequestDeviceConfigurationChange(AudioObjectID deviceObjectID,
        UInt64 changeAction,
        void* changeInfo);

    // @}

    //! @name Storage API
    //! @{

    //! Handle request to copy data from persistent storage.
    //!
    //! Called by driver (via host vtable) when it wants to retrieve data associated
    //! with a key.
    //!
    //! See Driver::GetStorage().
    //!
    //! @remarks
    //!  Default implementation calls CopyFromStorageImpl() and adds boilerplate
    //!  for tracing, locking, and (de)serialization.
    //!
    //!  Usually it's easier to override CopyFromStorageImpl() and related methods,
    //!  rather than this one, as it is more low-level.
    virtual OSStatus CopyFromStorage(CFStringRef key, CFPropertyListRef* outData) const;

    //! Handle request to write data to persistent storage.
    //!
    //! Called when the plugin wants to store data associated with a key.
    //! Any existing data for the key is replaced.
    //!
    //! See Driver::GetStorage().
    //!
    //! @remarks
    //!  Default implementation calls WriteToStorageImpl() and adds boilerplate
    //!  for tracing, locking, and (de)serialization.
    //!
    //!  Usually it's easier to override WriteToStorageImpl() and related methods,
    //!  rather than this one, as it is more low-level.
    virtual OSStatus WriteToStorage(CFStringRef key, CFPropertyListRef data);

    //! Handle request to delete data from persistent storage.
    //!
    //! Called when the plugin wants to remove a key and its associated data.
    //!
    //! See Driver::GetStorage().
    //!
    //! @remarks
    //!  Default implementation calls DeleteFromStorageImpl() and adds boilerplate
    //!  for tracing, locking, and (de)serialization.
    //!
    //!  Usually it's easier to override DeleteFromStorageImpl() and related methods,
    //!  rather than this one, as it is more low-level.
    virtual OSStatus DeleteFromStorage(CFStringRef key);

    // @}

protected:
    //! @name Implementation of virtual events
    //! @{

    //! Default implementation for HasAvailEvents().
    //! Return size of lock-free event queue.
    virtual UInt64 PendingEventsImpl() const;

    //! Default implementation for WaitEvent().
    //! Reads event from lock-free event queue.
    virtual std::shared_ptr<VirtualEventInfo> WaitEventImpl(
        std::optional<std::chrono::steady_clock::time_point> deadline = {});

    //! Default implementation for ReadEvent().
    //! Reads event from lock-free event queue.
    virtual std::shared_ptr<VirtualEventInfo> ReadEventImpl();

    //! Default implementation for AllocateEvent().
    //! Allocates event from lock-free event pool.
    virtual std::shared_ptr<VirtualEventInfo> AllocateEventImpl(
        VirtualEventType eventType);

    //! Default implementation for EnqueueEvent().
    //! Adds event to lock-free event queue.
    virtual void EnqueueEventImpl(std::shared_ptr<VirtualEventInfo> event);

    //! Default implementation for AbortEvents().
    //! Marks event queue as closed.
    virtual void AbortEventsImpl();

    //! Report event to tracer.
    //! Event may be null.
    virtual void TraceEventImpl(const char* operation,
        const std::shared_ptr<VirtualEventInfo>& event);

    // @}

    //! @name Implementation of virtual IO timer
    //! @{

    //! Get current time in same domain as IO ticks time.
    //! Used to decide how long to wait till next tick.
    //! @remarks
    //!  Default implementation returns real time from steady (a.k.a. monotonic)
    //!  clock. Override it if you want to use some sort of fake time.
    virtual std::chrono::steady_clock::time_point GetCurrentTimeImpl() const;

    //! Check if current time is in tick safety zone.
    //! Used to decide if we're allowed to process events or next I/O tick is too close.
    //!
    //! @remarks
    //!  Default implementation returns true if TicksPerSecond is non-zero, TickSafetyZone
    //!  is non-zero, and current time is within safety zone before next tick time.
    //!
    //! @note
    //!  @p currentTime is a value recently got from GetCurrentTimeImpl(). The function is
    //!  expected to use it instead of querying OS again, to ensure that adjustent calls
    //!  with same time would produce consistent results.
    virtual bool IsSafetyZoneImpl(
        std::chrono::steady_clock::time_point currentTime) const;

    //! Get next virtual tick info.
    //! Returns nullopt if no tick event should be generated.
    //!
    //! @remarks
    //!  Default implementation initializes timer on first call and schedules
    //!  first tick immediately. Each subsequent tick is one period later.
    //!
    //! @note
    //!  @p currentTime is a value recently got from GetCurrentTimeImpl(). The function is
    //!  expected to use it instead of querying OS again, to ensure that adjustent calls
    //!  with same time would produce consistent results.
    virtual std::optional<VirtualEventInfo::IOTimerTickInfo> GetNextTickImpl(
        std::chrono::steady_clock::time_point currentTime) const;

    //! Advance virtual tick counter.
    //! Returns true if tick was advanced and event should be generated,
    //! or false if tick is refused or already happened earlier.
    //!
    //! @remarks
    //!  Default implementation uses compare-and-swap to ensure tick counter
    //!  only grows (never decreases) and refuses non-monotonic updates.
    virtual bool DoNextTickImpl(std::chrono::steady_clock::time_point currentTime,
        SInt64 tickNum);

    //! Trace time remaining to next tick.
    //! Called from WaitEvent() every time before sleep.
    //!
    //! @remarks
    //!  - @p safetyZone is true if WaitEvent() wait for safety zone end.
    //!  - @p wakeupTime specifies when WaitEvent() plan to wake up.
    void TraceTickImpl(const VirtualEventInfo::IOTimerTickInfo& tickInfo,
        bool safetyZone,
        const std::chrono::steady_clock::time_point& currentTime,
        const std::chrono::steady_clock::time_point& wakeupTime);

    // @}

    //! @name Implementation of virtual storage
    //! @{

    //! Default implementation for CopyFromStorage().
    //! Uses in-memory storage.
    virtual OSStatus CopyFromStorageImpl(const std::string& key,
        std::vector<UInt8>& outData) const;

    //! Default implementation for WriteToStorage().
    //! Uses in-memory storage.
    virtual OSStatus WriteToStorageImpl(const std::string& key,
        const std::vector<UInt8>& data);

    //! Default implementation for DeleteFromStorage().
    //! Uses in-memory storage.
    virtual OSStatus DeleteFromStorageImpl(const std::string& key);

    // @}

private:
    // Extract VirtualHost instance from AudioServerPlugInHostRef.
    static VirtualHost* GetHost(AudioServerPlugInHostRef inHost);

    // Static jumper functions (called from plugin via AudioServerPlugInHostRef)
    // These extract the VirtualHost instance and forward to virtual methods.
    static OSStatus PropertiesChangedJumper(AudioServerPlugInHostRef inHost,
        AudioObjectID inObjectID,
        UInt32 inNumberAddresses,
        const AudioObjectPropertyAddress* inAddresses);

    static OSStatus CopyFromStorageJumper(AudioServerPlugInHostRef inHost,
        CFStringRef inKey,
        CFPropertyListRef* outData);

    static OSStatus WriteToStorageJumper(AudioServerPlugInHostRef inHost,
        CFStringRef inKey,
        CFPropertyListRef inData);

    static OSStatus DeleteFromStorageJumper(AudioServerPlugInHostRef inHost,
        CFStringRef inKey);

    static OSStatus RequestDeviceConfigurationChangeJumper(
        AudioServerPlugInHostRef inHost,
        AudioObjectID inDeviceObjectID,
        UInt64 inChangeAction,
        void* inChangeInfo);

    std::shared_ptr<VirtualEventInfo> GenerateTickEvent(
        const VirtualEventInfo::IOTimerTickInfo& tick);

    AudioServerPlugInHostInterface hostInterface_;

    const VirtualHostParameters params_;
    const std::shared_ptr<Tracer> tracer_;

    std::atomic<bool> abortFlag_{false};
    util::Semaphore sleepSem_;

    // virtual events
    util::ObjectPool<VirtualEventInfo> eventPool_;
    util::MpscQueue<VirtualEventInfo> eventQueue_;
    util::Semaphore eventSem_;
    std::atomic<UInt64> eventCount_{0};

    // virtual io timer
    mutable std::once_flag timerInitFlag_;
    mutable std::chrono::steady_clock::time_point timerStartTime_;
    mutable std::atomic<SInt64> timerTickNum_;

    // virtual storage
    mutable std::shared_mutex storageMutex_;
    std::unordered_map<std::string, std::vector<UInt8>> storage_;
};

} // namespace aspl
