name: "build"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        macos: [11, 12, latest]

    runs-on: macos-${{ matrix.macos }}
    name: macos-${{ matrix.macos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release build
        run: make release_build

      - name: Debug build
        run: make debug_build

      - name: Test
        run: make test

      - name: Example
        run: make example

      - name: Install
        run: sudo make install

  doxygen:
    runs-on: macos-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: Install tools
        run: brew install doxygen graphviz

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: make debug_build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: doxygen
          folder: html
          single-commit: true
